services:
  - type: web
    name: ma-scene
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    autoDeploy: true
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: USER_COUNTRY
        value: France
      - key: USER_CITY
        value: Paris
